artifact_uri: file:///C:/Users/HP/ml_pipeline_project/mlruns_clean/293023702705074199/fec4ca14dfad47bea0dbed3b491e3b1d/artifacts
end_time: 1751607812329
entry_point_name: ''
experiment_id: '293023702705074199'
lifecycle_stage: active
run_id: fec4ca14dfad47bea0dbed3b491e3b1d
run_name: placid-snail-354
source_name: ''
source_type: 4
source_version: ''
start_time: 1751607771100
status: 3
tags: []
user_id: HP
