artifact_uri: file:///C:/Users/HP/ml_pipeline_project/mlruns_clean/293023702705074199/1de505ccaebd48af97d1c41ad91fd5c6/artifacts
end_time: 1751607812425
entry_point_name: ''
experiment_id: '293023702705074199'
lifecycle_stage: active
run_id: 1de505ccaebd48af97d1c41ad91fd5c6
run_name: '1'
source_name: ''
source_type: 4
source_version: ''
start_time: 1751607812349
status: 3
tags: []
user_id: HP
